const fs = require('node:fs');
const path = require('node:path');
const sharp = require(require.resolve('sharp', {paths:[path.dirname(require.resolve('next/package.json'))]}));
const root=path.resolve(__dirname,'../..');
const source=path.join(root,'qa-output/density-blender');
const out=path.join(root,'public/assets/lessons/topic02/contour-density/dioramas');
fs.mkdirSync(out,{recursive:true});
(async()=>{
  const metadata={};
  const archive = process.argv.includes('--archive');
  const modes = archive ? ['relief','section'] : ['side'];
  for(const kind of ['gentle','steep','cliff']){
    metadata[kind]=archive
      ? JSON.parse(fs.readFileSync(path.join(source,kind+'-labels.json'),'utf8'))
      : {side:JSON.parse(fs.readFileSync(path.join(source,kind+'-side-labels.json'),'utf8'))};
    for(const mode of modes){
      await sharp(path.join(source,kind+'-'+mode+'.png')).webp({quality:92,alphaQuality:100}).toFile(path.join(out,kind+'-'+mode+'.webp'));
    }
  }
  fs.writeFileSync(path.join(root,'src/components/lessons/topic-02/contourDensityRenders.data.ts'),
    '// Generated by scripts/blender/package_density_renders.cjs. Camera-projected label anchors.\n'+
    'export const DENSITY_RENDER_LABELS = '+JSON.stringify(metadata,null,2)+' as const;\n');
  console.log('Packaged '+(modes.length*3)+' Blender renders and their projected label anchors.');
})();
