// Web delivery for the generated realistic finish of the Blender shape guides.
const fs = require('node:fs');
const path = require('node:path');
const sharp = require(require.resolve('sharp', { paths: [path.dirname(require.resolve('next/package.json'))] }));
const root = path.resolve(__dirname, '../..');
const source = path.join(root, 'design/blender/terrain-density/isolated-sides/appearance');
const out = path.join(root, 'public/assets/lessons/topic02/contour-density/dioramas');
(async () => {
  const metadata = {};
  for (const kind of ['gentle', 'steep', 'cliff']) {
    const input = path.join(source, kind + '.png');
    await sharp(input).resize(1200, 420).webp({ quality: 92, alphaQuality: 100 }).toFile(path.join(out, kind + '-natural.webp'));
    metadata[kind] = { side: JSON.parse(fs.readFileSync(path.join(root, 'qa-output/density-blender', kind + '-side-labels.json'), 'utf8')) };
  }
  fs.writeFileSync(path.join(root, 'src/components/lessons/topic-02/contourDensityRenders.data.ts'),
    '// Generated by scripts/blender/package_density_appearance.cjs. Blender shape-guide camera anchors.\n' +
    'export const DENSITY_RENDER_LABELS = ' + JSON.stringify(metadata, null, 2) + ' as const;\n');
  console.log('Packaged three realistic terrain illustrations.');
})();
