// GENERATED by scripts/maps/build-scale-sheets.mjs on 2026-10-08 — do not edit by hand.
// Orthophoto: Esri World Imagery (MapServer/export, EPSG:3857). Map: Israel Hiking Map Hebrew tiles
// (CC BY-NC-SA 3.0), mosaicked and cut to the same EPSG:3857 box. Sheets are 24 × 24 cm at their scale.
import type { LatLon, SheetGeometry } from './geo';

export type SheetId = '10k' | '50k' | '250k';
export type SheetMeta = SheetGeometry & {
  id: SheetId;
  corners: { sw: LatLon; ne: LatLon };
  ortho: { src: string; px: number };
  map: { src: string; px: number; zoom: number };
};

export const SHEET_IDS: readonly SheetId[] = ['10k', '50k', '250k'];

export const SHEETS: Record<SheetId, SheetMeta> = {
  '10k': {
    id: '10k',
    denominator: 10000,
    center: { lat: 32.687, lon: 35.39 },
    groundWidthM: 2400,
    sheetCm: 24,
    bbox3857: [3938172.373, 3852407.357, 3941021.186, 3855256.170],
    corners: { sw: { lat: 32.676230, lon: 35.377204 }, ne: { lat: 32.697769, lon: 35.402796 } },
    ortho: { src: '/assets/lessons/topic02/scene-scale/sheets/10k-ortho.webp', px: 1600 },
    map: { src: '/assets/lessons/topic02/scene-scale/sheets/10k-map.webp', px: 596, zoom: 15 },
  },
  '50k': {
    id: '50k',
    denominator: 50000,
    center: { lat: 32.687, lon: 35.39 },
    groundWidthM: 12000,
    sheetCm: 24,
    bbox3857: [3932474.747, 3846709.731, 3946718.811, 3860953.795],
    corners: { sw: { lat: 32.633137, lon: 35.326022 }, ne: { lat: 32.740830, lon: 35.453978 } },
    ortho: { src: '/assets/lessons/topic02/scene-scale/sheets/50k-ortho.webp', px: 1600 },
    map: { src: '/assets/lessons/topic02/scene-scale/sheets/50k-map.webp', px: 745, zoom: 13 },
  },
  '250k': {
    id: '250k',
    denominator: 250000,
    center: { lat: 32.687, lon: 35.39 },
    groundWidthM: 60000,
    sheetCm: 24,
    bbox3857: [3903986.618, 3818221.601, 3975206.941, 3889441.925],
    corners: { sw: { lat: 32.417363, lon: 35.070108 }, ne: { lat: 32.955825, lon: 35.709892 } },
    ortho: { src: '/assets/lessons/topic02/scene-scale/sheets/250k-ortho.webp', px: 1600 },
    map: { src: '/assets/lessons/topic02/scene-scale/sheets/250k-map.webp', px: 932, zoom: 11 },
  },
};

export const ATTRIBUTION = {
  ortho: 'תצ״א: Esri, Vantor, Earthstar Geographics, GIS User Community',
  map: 'מפה: Israel Hiking Map · © תורמי OpenStreetMap · CC BY-NC-SA 3.0',
} as const;
