// Generated by scripts/blender/package_density_appearance.cjs. Blender shape-guide camera anchors.
export const DENSITY_RENDER_LABELS = {
  "gentle": {
    "side": {
      "labels": [
        {
          "text": "20",
          "point": [
            23.934,
            46.12
          ]
        },
        {
          "text": "40",
          "point": [
            23.934,
            34.773
          ]
        },
        {
          "text": "60",
          "point": [
            23.934,
            23.426
          ]
        },
        {
          "text": "80",
          "point": [
            23.934,
            12.079
          ]
        }
      ],
      "ends": [
        [
          31.148,
          57.467
        ],
        [
          168.852,
          57.467
        ]
      ]
    }
  },
  "steep": {
    "side": {
      "labels": [
        {
          "text": "20",
          "point": [
            23.934,
            46.12
          ]
        },
        {
          "text": "40",
          "point": [
            23.934,
            34.773
          ]
        },
        {
          "text": "60",
          "point": [
            23.934,
            23.426
          ]
        },
        {
          "text": "80",
          "point": [
            23.934,
            12.079
          ]
        }
      ],
      "ends": [
        [
          31.148,
          57.467
        ],
        [
          168.852,
          57.467
        ]
      ]
    }
  },
  "cliff": {
    "side": {
      "labels": [
        {
          "text": "20",
          "point": [
            23.934,
            46.12
          ]
        },
        {
          "text": "40",
          "point": [
            23.934,
            34.773
          ]
        },
        {
          "text": "60",
          "point": [
            23.934,
            23.426
          ]
        },
        {
          "text": "80",
          "point": [
            23.934,
            12.079
          ]
        }
      ],
      "ends": [
        [
          31.148,
          57.467
        ],
        [
          168.852,
          57.467
        ]
      ]
    }
  }
} as const;
